
BLENDER="E:\Program Files\Blender Foundation\Blender 2.90\blender.exe"
DIST=../dist

all : \
    $(DIST)/room.pnct \
    $(DIST)/room.scene \

$(DIST)/room.scene : room.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "room.blend:Main" "$(DIST)/room.scene"

$(DIST)/room.pnct : room.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "room.blend:Main" "$(DIST)/room.pnct" 
